apiVersion: v1
items:
- apiVersion: external-secrets.io/v1beta1
  kind: ClusterSecretStore
  metadata:
    labels:
      app.kubernetes.io/instance: as-prod-config
    name: gcp-addysnip-secretstore
  spec:
    provider:
      gcpsm:
        auth:
          secretRef:
            secretAccessKeySecretRef:
              key: secret-access-credentials
              name: addysnip-gcpsm-secret
              namespace: external-secrets
        projectID: addysnip
- apiVersion: external-secrets.io/v1beta1
  kind: ClusterSecretStore
  metadata:
    labels:
      app.kubernetes.io/instance: config
    name: gcp-store
  spec:
    provider:
      gcpsm:
        auth:
          secretRef:
            secretAccessKeySecretRef:
              key: secret-access-credentials
              name: gcpsm-secret
              namespace: external-secrets
        projectID: adhp-386716
- apiVersion: external-secrets.io/v1beta1
  kind: ClusterSecretStore
  metadata:
    labels:
      app.kubernetes.io/instance: adh-configs
    name: vatsim-gcp-store
  spec:
    provider:
      gcpsm:
        auth:
          secretRef:
            secretAccessKeySecretRef:
              key: secret-access-credentials
              name: vatsim-gcpsm-secret
              namespace: external-secrets
        projectID: vatsim-adh
kind: List
metadata:
  resourceVersion: ""
