gloo:
  gatewayProxies:
    gatewayProxy:
      gatewaySettings:
        useProxyProto: true
  ingressProxy:
    service:
      extraAnnotations:
        service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
        service.beta.kubernetes.io/do-loadbalancer-hostname: cluster2.lb.addysnip.link
        service.beta.kubernetes.io/do-loadbalancer-tls-passthrough: "true"
