gloo:
  gatewayProxies:
    gatewayProxy:
      gatewaySettings:
        useProxyProto: true
      service:
        extraAnnotations:
          service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
          service.beta.kubernetes.io/do-loadbalancer-hostname: lb.ca.hawton.cloud
          service.beta.kubernetes.io/do-loadbalancer-tls-passthrough: "true"
