apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: configs
resources:
- base/cert-manager-ClusterIssuer.yaml
- base/cert-manager-external-secret.yaml
- base/external-secret-clustersecretstore.yaml
